#!/bin/bash
# chkconfig: 234 20 80
# description: Zookeeper basic start/shutdown script
#
# @author Cameron Gregory, http://www.bloke.com/

JAVA_HOME=/usr/java/default
export JAVA_HOME
ZOOKEEPER_HOME=/www/kafka
ZOOKEEPER_USER=cameron
SHUTDOWN_WAIT=20

NAME="$(basename $0)"
unset ISBOOT
if [ "${NAME:0:1}" = "S" -o "${NAME:0:1}" = "K" ]; then
    NAME="${NAME:3}"
    ISBOOT="1"
fi

# Get instance specific config file
if [ -r "/etc/sysconfig/${NAME}" ]; then
    . /etc/sysconfig/${NAME}
fi

zookeeper_pid() {
echo `ps aux | grep " org.apache.zookeeper.server.quorum.QuorumPeerMain ./config/zookeeper.properties" | grep -v grep | awk '{ print $2 }'`
}
 
start() {
	pid=$(zookeeper_pid)
	ret=0
	if [ -n "$pid" ]; then
		echo "Zookeeper is already running (pid: $pid)"
		ret=1;
	else
		echo -n "Starting zookeeper: "
  		#ulimit -n 65536
  		#ulimit -s 10240
  		#ulimit -c unlimited
		cd $ZOOKEEPER_HOME
		su ${ZOOKEEPER_USER} -c "./bin/zookeeper-server-start.sh ./config/zookeeper.properties" >> /var/log/zookeeper.log 2>&1 &
		ret=$?
		echo "done."
	fi
	return $ret;
}
stop() {
	pid=$(zookeeper_pid)
	if [ -n "$pid" ]; then
		echo -n "Shutting down zookeeper: "
		cd $ZOOKEEPER_HOME
		kill $pid
		#${STOP_ZOOKEEPER}
		let kwait=$SHUTDOWN_WAIT
		count=0;
		until [ `ps -p $pid | grep -c $pid` = '0' ] || [ $count -gt $kwait ]; do
			echo -n -e "\nwaiting for processes to exit";
			sleep 1
			let count=$count+1;
		done
		if [ $count -gt $kwait ]; then
			echo -e "\nkilling processes which didn't stop after $SHUTDOWN_WAIT seconds"
			kill -9 $pid
			sleep 1
		else
			echo " Done"
		fi
	else
		echo "Zookeeper is not running"
		return 1;
	fi
	
	return 0;
}
abort() {
	pid=$(zookeeper_pid)
	if [ -n "$pid" ]; then
		echo -n "Shutting down zookeeper: "
		cd $ZOOKEEPER_HOME
		kill $pid
		let kwait=1
		count=0;
		until [ `ps -p $pid | grep -c $pid` = '0' ] || [ $count -ge $kwait ]; do
			echo -n -e "\nwaiting for processes to exit";
			sleep 1
			let count=$count+1;
		done
		if [ $count -ge $kwait ]; then
			echo -e "\nkilling processes which didn't stop after $kwait seconds"
			kill -9 $pid
			sleep 1
		else
			echo " Done"
		fi
	else
		echo "Zookeeper is not running"
	fi
	
	return 0
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	abort)
		abort
		;;
	restart)
		stop
		start
		;;
	status)
		pid=$(zookeeper_pid)
		if [ -n "$pid" ]; then
			echo "Zookeeper is running with pid: $pid"
		else
			echo "Zookeeper is not running"
		fi
		;; 
	*)
		echo "Usage: $0 {start|stop|restart|status|abort}"
esac
exit 0
